apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-autoscaling
  labels:
    app: my-k8s-application
spec:
  replicas: 2
  selector:
    matchLabels:
      project: mossad
  template:
    metadata:
      labels:
        project: mossad
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscaling
spec:
  scaleTargetRef:
    apiVersion: app/v2beta1v1
    kind: Deployment
    name: nginx-deployment-autoscaling
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80