apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-replicase
  labels:
    app: my-k8s-application
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
