version: '3'
services:

  ssh-ms3:
    image: pavelinnokentevichgalanin/8sem-rsiot-ms3
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - ${MS3_DOCKER_PORT_NODEJS}:${MS3_PORT}
    volumes:
      - ./ssh.env:/app/prod.env
    command: npm run start:prod

  ssh-watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=150
      - WATCHTOWER_LABEL_ENABLE=true
