version: '3'
services:

  dev-db:
    image: postgres
    environment:
      POSTGRES_USER: ${DMS_USER}
      POSTGRES_PASSWORD: ${DMS_PASS}
      POSTGRES_DB: ${DMS_NAME}
    ports:
      - ${OUT_PORT_DTB}:5432
    volumes:
      - ./docker/dev/postgres/data:/var/lib/postgresql/data

  dev-adminer:
    image: adminer
    restart: always
    ports:
      - ${OUT_PORT_ADM}:8080
    depends_on: 
      - dev-db
