version: '3'
services:

  prod-db:
    image: postgres
    environment:
      POSTGRES_USER: ${MS2_DB_USER}
      POSTGRES_PASSWORD: ${MS2_DB_PASS}
      POSTGRES_DB: ${MS2_DB_NAME}
    ports:
      - ${MS2_DOCKER_PORT_DATABASE}:5432
    volumes:
      - ./docker/prod/postgres/data:/var/lib/postgresql/data

  prod-adminer:
    image: adminer
    restart: always
    depends_on: 
      - prod-db
    ports:
      - ${MS2_DOCKER_PORT_ADMINER}:8080

  prod-backend:
    build:
      context: .
      dockerfile: ./prod.Dockerfile
    ports:
      - ${MS2_DOCKER_PORT_NODEJS}:${MS2_PORT}
    depends_on: 
      - prod-db
    command: sh prod.run.sh
